# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
matrix:
  include:
  - r: devel
  - r: release
    after_success:
      - Rscript -e 'covr::codecov()'
  - r: 3.5
  - r: 3.4
  - r: 3.3
  - r: 3.2
sudo: false
